name: ecommerce_crud_operation
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  permission_handler: ^10.0.1
  image_picker: ^0.8.5+3
  http_parser: ^4.0.1
  cached_network_image: ^3.2.2
  pretty_dio_logger: ^1.1.1
  file_picker: ^5.2.0
  flutter_colorpicker: ^1.0.3
  dartz: ^0.10.1
  flutter_form_builder: ^7.6.0


  dio: ^4.0.6
  internet_connection_checker: ^1.0.0+1
  get: 4.6.5
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

